FileVersion = 1
Projects = {Minesweeper = {Path = "code/Minesweeper.Game"}, raylib-beef = {Path = "vendor/raylib-beef/raylib-beef"}, BJSON = {Path = "vendor/BJSON/BJSON"}, MinesweeperWasm = {Path = "code/Minesweeper.Wasm"}, MinesweeperDesktop = {Path = "code/Minesweeper.Desktop"}, MinesweeperNewgrounds = {Path = "code/Minesweeper.Newgrounds"}}
WorkspaceFolders = {Dependencies = ["BJSON", "raylib-beef", "corlib"]}

[Workspace]
StartupProject = "MinesweeperWasm"

[Configs.Debug.Win64]
ConfigSelections = {raylib-beef = {Config = "StaticDebug"}}

[Configs.Debug.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Paranoid.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false

[Configs.Release.Win64]
ConfigSelections = {raylib-beef = {Config = "StaticRelease"}}

[Configs.Test.wasm32]
AllocType = "CRT"
EnableObjectDebugFlags = false
EmitObjectAccessCheck = false
