FileVersion = 1
Dependencies = {corlib = "*", MinesweeperLibrary = "*"}

[Project]
Name = "MinesweeperAndroid"
TargetType = "BeefLib"
StartupObject = "BeefAndroid.Program"
DefaultNamespace = "BeefAndroid"
