FileVersion = 1
Dependencies = {corlib = "*", MinesweeperLibrary = "*"}

[Project]
Name = "MinesweeperGUI"
TargetType = "BeefGUIApplication"
StartupObject = "MinesweeperGUI.Program"

[Platform.Windows]
IconFile = "$(WorkspaceDir)/assets/icon.ico"
Description = "Minesweeper with levels"
Product = "Minesweeper+"
Copyright = "© Boxsubmus"
FileVersion = "1.0.2.0"
ProductVersion = "1.0.2.0"
