FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*", BJSON = "*"}

[Project]
Name = "Minesweeper.Game"
TargetType = "BeefLib"
StartupObject = "Minesweeper.Program"
DefaultNamespace = "Minesweeper"

[Configs.Debug.wasm32]
OtherLinkFlags = "$(LinkFlags) -sFETCH=1"
PreprocessorMacros = ["DEBUG", "NEWGROUNDS"]

[Configs.Release.wasm32]
OtherLinkFlags = "$(LinkFlags)  -sFETCH=1"
PostBuildCmds = ["CopyToDependents(\"$(WorkspaceDir)/wasm/index.html\")"]
