FileVersion = 1
Dependencies = {corlib = "*", Minesweeper = "*"}

[Project]
Name = "MinesweeperNewgrounds"
TargetType = "BeefGUIApplication"
StartupObject = "Minesweeper.Newgrounds.Program"
DefaultNamespace = "Minesweeper.Newgrounds"

[Configs.Release.wasm32]
PostBuildCmds = ["CopyFilesIfNewer(\"$(WorkspaceDir)/wasm/newgrounds/index.html\", \"$(BuildDir)\")"]
