FileVersion = 1
Dependencies = {corlib = "*", Minesweeper = "*"}

[Project]
Name = "MinesweeperDesktop"
TargetType = "BeefGUIApplication"
StartupObject = "Minesweeper.Desktop.Program"
DefaultNamespace = "Minesweeper.Desktop"

[Platform.Windows]
IconFile = "$(WorkspaceDir)/assets/icon.ico"
Description = "Minesweeper with levels"
Product = "Minesweeper+"
Copyright = "© Boxsubmus"
FileVersion = "1.0.0.0"
ProductVersion = "1.0.0.0"
